# Generated by Django 5.0.6 on 2024-06-15 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_topic_message_user_room_host_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-created", "-updated"]},
        ),
    ]
