# Generated by Django 5.0.6 on 2024-06-18 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_message_options_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
